export const words = [
  // 3 Letters
  "API", "BIN", "CPU", "DOM", "GIT", "IDE", "LOG", "NET", "URL", "VAR", "BIT", "BOT", "MAP", "SQL", "HEX", "KEY", "TAG", "WEB", "ZIP",

  // 4 Letters
  "BYTE", "CODE", "DATA", "FORK", "HASH", "HOST", "JAVA", "NODE", "NULL", "PUSH", "VOID", "BASE", "BLOB", "BOOL", "CORE", "DUMP", "EDGE", "FILE", "GATE", "GULP", "HTML", "JSON", "LAMP", "LINK", "LINT", "LOOP", "MAIN", "PATH", "PERL", "PING", "PORT", "PYON", "RUST", "SASS", "TEST", "TREE", "UNIT", "WASM",

  // 5 Letters
  "ARRAY", "ASYNC", "BUILD", "CACHE", "CLASS", "DEBUG", "ERROR", "FETCH", "FLOAT", "INDEX", "LOGIC", "QUERY", "STACK", "ABORT", "ALGO", "AWAIT", "BREAK", "CHILD", "CLOUD", "EVENT", "FIELD", "FRAME", "GRAPH", "INPUT", "LAYER", "LOCAL", "MERGE", "MOUNT", "PATCH", "PIXEL", "PROXY", "QUEUE", "REACT", "REDUX", "SHELL", "SHIFT", "SLICE", "STATE", "SUPER", "TRACE", "TRASH", "WHILE", "WRITE",

  // 6 Letters
  "BUFFER", "COMMIT", "DEPLOY", "DOCKER", "EDITOR", "IMPORT", "KERNEL", "OBJECT", "PYTHON", "RENDER", "SCRIPT", "SOURCE", "STRING", "SYNTAX", "ASSERT", "BINARY", "CHROME", "CLIENT", "CONFIG", "COOKIE", "DELETE", "DOMAIN", "ENGINE", "EXPORT", "EXTEND", "FILTER", "FORMAT", "GITHUB", "HEADER", "LAYOUT", "MARKUP", "METHOD", "MODULE", "NESTED", "OUTPUT", "PACKET", "PARAMS", "PARENT", "REDUCE", "RETURN", "SERVER", "SOCKET", "SPREAD", "STREAM", "SWITCH", "TARGET", "THREAD", "TOGGLE", "UPDATE", "UPLOAD", "VALUES", "WINDOW",

  // 7 Letters
  "BOOLEAN", "CLOSURE", "COMPILE", "CONSOLE", "DYNAMIC", "ELEMENT", "LIBRARY", "NETWORK", "PROMISE", "RUNTIME", "STORAGE", "ADAPTER", "ANGULAR", "ARCHIVE", "BACKEND", "COMMAND", "CONTENT", "CONTEXT", "DEFAULT", "DESKTOP", "DEVELOP", "DISPLAY", "EXECUTE", "EXTRACT", "FACTORY", "FEATURE", "FORTRAN", "GENERIC", "HANDLER", "HASHTAG", "ITERATE", "KEYWORD", "MESSAGE", "MONGODB", "OFFLINE", "OPTIMAL", "PACKAGE", "PARALLEL", "PARSING", "PATTERN", "POINTER", "PROCESS", "PROGRAM", "PROJECT", "REPLACE", "REQUEST", "REVERSE", "ROUTING", "SCALING", "SERVICE", "SESSION", "SNIPPET", "STAGING", "SUPPORT", "TOOLBAR", "TRIGGER", "UNKNOWN", "UPGRADE", "UTILITY", "VERSION", "VIRTUAL", "WEBHOOK",

  // 8 Letters
  "CALLBACK", "COMPILER", "DATABASE", "FRONTEND", "FUNCTION", "INSTANCE", "TERMINAL", "VARIABLE", "ABSTRACT", "ARGUMENT", "ASSEMBLY", "BACKBONE", "BREAKING", "CAPACITY", "CHIPSET", "CONSTANT", "CONTINUE", "CRITICAL", "CYBERNET", "DEBUGGER", "DELEGATE", "DOCUMENT", "ENDPOINT", "ETHERNET", "EXTERNAL", "FIREWALL", "GRADIENT", "HARDWARE", "INFINITY", "INHERITS", "INTERNAL", "ITERATOR", "LANGUAGE", "LISTENER", "MANIFEST", "METADATA", "MODIFIER", "MUTATION", "OPERATOR", "OVERFLOW", "OVERRIDE", "PIPELINE", "PLATFORM", "PORTABLE", "PROTOCOL", "READABLE", "READONLY", "RECOVERY", "REGISTRY", "RESOURCE", "RESPONSE", "ROLLBACK", "SECURITY", "SELECTOR", "SEQUENCE", "SOFTWARE", "SPECIFIC", "STANDARD", "TEMPLATE", "TRANSFER", "VALIDATE", "VIEWPORT", "WORKFLOW"
];

// these new words.js has programming themed words.